# Generated by Django 3.1.4 on 2021-05-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcu_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='stars',
            field=models.IntegerField(default=0),
        ),
    ]
