# Generated by Django 3.1.4 on 2021-04-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mcu_site', '0002_auto_20210405_0258'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDetails',
            fields=[
                #('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('director', models.CharField(max_length=2048)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
