# Generated by Django 3.1.7 on 2021-04-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcu_site', '0002_auto_20210425_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.CharField(default='hi', max_length=32),
            preserve_default=False,
        ),
    ]
