# Generated by Django 3.1.4 on 2021-04-05 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcu_site', '0003_moviedetails'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='moviedetails',
            table='moviedetails',
        ),
    ]
